/**
 * This program creates a simple "hash" of
 * a person's name. A hash is an integer that is
 * mathematically derived from another object.
 * In this case, a string (the first and last name)
 * is accessed character by character and the hash
 * is built up from a number generated by each character.
 * While this function does not necessarily produce
 * unique hashes (different names can hash to the
 * same value), there is a relatively low possibility
 * of a "collision" with a class of roughly 400 students.
 *
 * We will learn more about hashing later this quarter!
 */

#include <iostream>
#include <string>
#include "console.h"
#include "simpio.h"  // for getLine
using namespace std;

/*
 * File: AddThreeNumbers.cpp
 * -------------------------
 * This program adds three floating-point numbers and prints their sum.
 */

int main() {
    double n1, n2, n3;
    cout << "This program adds three numbers." << endl;
    cout << "1st number: ";
    cin >> n1;
    cout << "2nd number: ";
    cin >> n2;
    cout << "3rd number: ";
    cin >> n3;

    double sum = n1 + n2 + n3;
    cout << "The sum is " << sum << endl;

    return 0;
}
